apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-app-deployment
  namespace: fut
  labels:
    app: article-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: article-app
  template:
    metadata:
      labels:
        app: article-app
    spec:
      containers:
      - name: article-app
        image: shivanshudwivedi/article:0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
#        resources:
#          limits:
#            memory: "512Mi"
#          requests:
#            memory: "256Mi"
        env:
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: supabase-key
        - name: SUPABASE_URL
          valueFrom:
            configMapKeyRef:
              name: service-urls
              key: supabase-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: openai-key
        - name: FLASK_APP
          value: "ArticleApp.py"
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
        - name: FLASK_ENV
          value: "production"