apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-app-deployment
  namespace: fut
  labels:
    app: article-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: article-app
  template:
    metadata:
      labels:
        app: article-app
    spec:
      containers:
      - name: article-app
        image: shivanshudwivedi/article:final
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "256Mi"
        env:
        - name: SUPABASE_URL
          value: "https://hbrecxmlkcpcwmoijrke.supabase.co"
        - name: SUPABASE_KEY
          value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhicmVjeG1sa2NwY3dtb2lqcmtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTMyNDk3MjIsImV4cCI6MjAyODgyNTcyMn0.2Oubd4u4Ehw2XHCynBQEbxCbugJ88tGzsDIsm6xxJik"
        - name: OPENAI_API_KEY
          value: "sk-proj-VbqYzw4WCXwHrOIUPwyKT3BlbkFJ5DL4VMQ56kwM3bp1UgFy"
        - name: FLASK_APP
          value: "ArticleApp.py"
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
        - name: FLASK_ENV
          value: "production"
