apiVersion: apps/v1
kind: Deployment
metadata:
  name: football-api-deployment
  namespace: fut
  labels:
    app: football-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: football-api
  template:
    metadata:
      labels:
        app: football-api
    spec:
      containers:
      - name: football-api
        image: shivanshudwivedi/footballapi-addfixtures:0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: RAPIDAPI_KEY
            valueFrom:
              secretKeyRef:
                name: api-keys
                key: rapid-api-key
          - name: SUPABASE_KEY
            valueFrom:
              secretKeyRef:
                name: api-keys
                key: supabase-key
          - name: SUPABASE_URL
            valueFrom:
              configMapKeyRef:
                name: service-urls
                key: supabase-url
          - name: WEATHER_API_URL
            valueFrom:
              configMapKeyRef:
                name: service-urls
                key: weather-api-url
          - name: RAPIDAPI_URL
            valueFrom:
              configMapKeyRef:
                name: service-urls
                key: rapid-api-url
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
