apiVersion: apps/v1
kind: Deployment
metadata:
  name: football-api-deployment
  namespace: fut
  labels:
    app: football-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: football-api
  template:
    metadata:
      labels:
        app: football-api
    spec:
      containers:
      - name: football-api
        image: shivanshudwivedi/footballapi-addfixtures:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: SUPABASE_URL
          value: "https://hbrecxmlkcpcwmoijrke.supabase.co"
        - name: SUPABASE_KEY
          value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhicmVjeG1sa2NwY3dtb2lqcmtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTMyNDk3MjIsImV4cCI6MjAyODgyNTcyMn0.2Oubd4u4Ehw2XHCynBQEbxCbugJ88tGzsDIsm6xxJik"
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
