apiVersion: v1
kind: Service
metadata:
  name: fut-website-service
spec:
  type: LoadBalancer  # This type exposes the service outside the cluster
  ports:
    - port: 80  # The port that the service exposes externally
      targetPort: 5173  # The
