name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push ArticleGenerator
      uses: docker/build-push-action@v2
      with:
        context: ./ArticleGenerator
        file: ./ArticleGenerator/Dockerfile
        push: true
        tags: shivanshudwivedi/article-generator:latest
        platforms: linux/amd64,linux/arm64

    - name: Build and push FootballAPI
      uses: docker/build-push-action@v2
      with:
        context: ./FootballAPI
        file: ./FootballAPI/Dockerfile
        push: true
        tags: shivanshudwivedi/football-api:latest
        platforms: linux/amd64,linux/arm64

    - name: Build and push WeatherAPI
      uses: docker/build-push-action@v2
      with:
        context: ./WeatherAPI
        file: ./WeatherAPI/Dockerfile
        push: true
        tags: shivanshudwivedi/weather-api:latest
        platforms: linux/amd64,linux/arm64

    - name: Build and push Website
      uses: docker/build-push-action@v2
      with:
        context: ./Website
        file: ./Website/Dockerfile
        push: true
        tags: shivanshudwivedi/website:latest
        platforms: linux/amd64,linux/arm64

    - name: Clean up Docker images
      run: |
        docker rmi yourusername/article-generator:latest
        docker rmi yourusername/football-api:latest
        docker rmi yourusername/weather-api:latest
        docker rmi yourusername/website:latest
